### ISSUE TITLE
Testing: "Set inverse property values" toggle in batch edit form

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/InverseProperties#4]
On the main branch, users can now batch-update existing resources with inverse properties using the new "Set inverse property values" checkbox. Checking this box should create inverse values for existing resources that didn't have inverse values.

**Comment by allanaaa** [comment]
This worked! Which is great because using IR with CSV Import appears not to work (i.e., setting the resource template and then filling out an IR-set field doesn't create the inverses). 

I'll hold off on adding a line to the docs until a new release. My guess is this doesn't seem big enough to occasion a release on its own?

**Comment by jimsafley** [comment]
This change fixes a bug so I'm going to make a make a new release today.
